language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: 
  - python manage.py run_test
  - coverage run --source='.'  manage.py run_test
  - coverage report

after_script:
  - codeclimate-test-reporter

# push report to coveralls.io
after_success:
  - coveralls